# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190430_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticleTag'),
        ),
    ]
